model_name: x3d_m 
num_epochs: 20
output_dir: /volume/DeepRV/outputs/
# model_path: /volume/x3d_m_4_72_2_SGD_new_20241024-032313_fxxpabtv/best.pt
model_path: /media/data1/fzahra/x3d_m_4_72_2_SGD_new_20241024-032313_fxxpabtv/best.pt
data_filename: /volume/DeepRV/input/filtered_deep_rv_data_alpha_updated.csv
root: "."
datapoint_loc_label: FileName
use_amp: true
mean: [112.24039459228516,112.24039459228516, 112.24039459228516]
std: [39.012229919433594,39.012229919433594,39.012229919433594]
frames: 72
device: cuda
period: 2
pretrained: false
seed: 0
num_workers: 8
batch_size: 4
label_smoothing: null
label_smoothing_value: null
class_weights: null
loss: bce_logit_loss
task: classification
num_classes: 1
run_test: true
rand_augment: false
resize: 256
apply_mask: false
view_count: null
save_best: loss
resume: false